### PR TITLE
Added support a russian language

### LINKED ISSUE #3: Multi language support
Is it possible to add support for several languages to this mod?
or need to fork this mod.

### PR DESCRIPTION
**Pull request by EndrII**
fix #3 

There is a question.
all messages like this message:
```
A prominent leader of %1 has called for the destruction of %2 during a state of the union address. Relations have greatly worsened.
```

are they random, or is the corresponding event  generating them?

### CODE REVIEW

**Comment by EndrII** [comment]
And update please steam version of this mod.

**Comment by DeadAirRT** [comment]
So the %1 are variables that are defined by the script itself, I put the code in comments above the line to give a hint. For example $Factiononenames would be the name of the first faction involved in the event.

I actually don't manage the steam versions but I'll look into possibly taking over. Someone had offered to do the uploading for me but I guess they are not updating as much as I hoped (I've been pushing a lot of updates recently so it's partially my fault)

**Comment by EndrII** [comment]
everything is ready for merge

**Comment by DeadAirRT** [comment]
So I found out I missed a lot of hard coded text. Would you mind updating your file when you get a chance?

**Comment by EndrII** [comment]
All done!

**Comment by DeadAirRT** [comment]
Thank you!

**Comment by EndrII** [comment]
I really hope to see this soon in Steam, since simply copying the contents of the repository to the extensions folder does not include the Russian language.

**Comment by DeadAirRT** [comment]
I'm waiting for Egosoft to fix a bug with their steam mod uploader atm before I can push anymore patches.

**Pull request merged**
